### ISSUE TITLE
Error: error:09091064:PEM routines:PEM_read_bio_ex:bad base64 decode

### ISSUE THREAD

**Issue by tanvirstreame** [shahriar-shojib/nagad-payment-gateway#5]
After giving all the keys it is showing this error -

Error: error:09091064:PEM routines:PEM_read_bio_ex:bad base64 decode
    at Object.<anonymous> (internal/crypto/cipher.js:63:12)
    at NagadGateway.encrypt (J:\nagad\node_modules\nagad-payment-gateway\dist\index.js:52:41)
    at NagadGateway.createPayment (J:\nagad\node_modules\nagad-payment-gateway\dist\index.js:140:33)
    at J:\nagad\index.js:16:32
    at Object.<anonymous> (J:\nagad\index.js:28:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  library: 'PEM routines',
  function: 'PEM_read_bio_ex',
  reason: 'bad base64 decode',
  code: 'ERR_OSSL_PEM_BAD_BASE64_DECODE'

**Comment by shahriar-shojib** [comment]
Hi can you please send me a snippet of how you constructed the nagad class?

**Comment by shahriar-shojib** [comment]
if you're providing a path, consider adding `isPath: true` when constructing nagad

**Comment by shahriar-shojib** [comment]
Closing this since there is no activity in this issue
